In [1]:
import pymysql

In [2]:
db = pymysql.connect(host='127.0.0.1', user='ysm', password='0504',
                     db='hospitaldb', charset='utf8')
cur = db.cursor()

## **table 생성**

**MedicalField table**

In [141]:
cur.execute("""
    CREATE TABLE MedicalFields (
        field_id INT PRIMARY KEY,
        majorfield VARCHAR(50) NOT NULL,
        minorfield VARCHAR(50) NULL DEFAULT NULL
    )
""")

0

**Doctor table**

In [144]:
cur.execute("""
    CREATE TABLE Doctors (
        doctor_id INT PRIMARY KEY,
        field_id INT,
        doctor_name VARCHAR(10) NOT NULL,
        specialized_field VARCHAR(50) NULL DEFAULT NULL,
        doctor_birth DATE NOT NULL,
        doctor_phone VARCHAR(20) NULL DEFAULT NULL,
        doctor_email VARCHAR(50) NULL DEFAULT NULL,

        CONSTRAINT fk_field_id FOREIGN KEY (field_id) 
            REFERENCES MedicalFields(field_id)
    )
""")

0

**Patient table**

In [143]:
cur.execute("""
    CREATE TABLE Patients (
        patient_id INT PRIMARY KEY,
        patient_name VARCHAR(50) NOT NULL,
        patient_sex CHAR(2) NULL DEFAULT NULL,
        patient_birth DATE NOT NULL,
        patient_phone VARCHAR(20) NULL DEFAULT NULL
    )
""")

0

**Diseases table**

In [142]:
cur.execute("""
    CREATE TABLE Diseases (
        disease_id INT PRIMARY KEY,
        disease_name VARCHAR(50) NOT NULL
    )
""")

0

**MedicalRecord table**

In [145]:
cur.execute("""
    CREATE TABLE MedicalRecords (
        record_id INT PRIMARY KEY,
        patient_id INT,
        doctor_id INT,
        disease_id INT,
        record_year VARCHAR(10) NOT NULL,
        record_month VARCHAR(2) NOT NULL,
        record_day VARCHAR(2) NOT NULL,
        cost FLOAT NULL DEFAULT NULL,

        CONSTRAINT fk_patient_id FOREIGN KEY (patient_id) 
            REFERENCES Patients(patient_id),
        CONSTRAINT fk_doctor_id FOREIGN KEY (doctor_id) 
            REFERENCES Doctors(doctor_id),
        CONSTRAINT fk_disease_id FOREIGN KEY (disease_id) 
            REFERENCES Diseases(disease_id)
    )
""")

0

## **데이터 확인 및 생성**

### 진료과 데이터

In [90]:
# 진료과 내역 데이터
field = pd.read_csv("fields.csv")
print(field.head(),'\n')
print(field.tail())

   field_id majorfield minorfield
0         1         내과       감염내과
1         2         내과      내분비내과
2         3         내과     류마티스내과
3         4         내과      소화기내과
4         5         내과       신장내과

    field_id majorfield minorfield
43        44         기타         치과
44        45         기타        피부과
45        46         기타       핵의학과
46        47         기타   심장혈관흉부외과
47        48         기타      입원의학과

### 환자 더미데이터

In [126]:
from faker import Faker
import random

fake = Faker('ko_KR')

# 가짜 환자 데이터 생성
def generate_fake_patient():
    id = random.randint(1, 1000)
    name = fake.name()
    sex = random.choice(['남자', '여자'])
    birthday = fake.date_of_birth(minimum_age=18, maximum_age=90)
    formatted_birthday = birthday.strftime('%Y-%m-%d')
    phone = '010' + str(fake.random_number(digits=8))

    return {
        'patient_id': id,
        'patient_name': name,
        'patient_sex': sex,
        'patient_birth': formatted_birthday,
        'patient_phone': phone,
    }

fake_patient_data1 = [generate_fake_patient() for _ in range(90)]
for patient in fake_patient_data1:
    print(patient)

{'patient_id': 64, 'patient_name': '최영길', 'patient_sex': '남자', 'patient_birth': '1941-07-20', 'patient_phone': '0104968477'}
{'patient_id': 721, 'patient_name': '백정남', 'patient_sex': '여자', 'patient_birth': '1993-01-20', 'patient_phone': '0108497486'}
{'patient_id': 817, 'patient_name': '최지혜', 'patient_sex': '남자', 'patient_birth': '1986-07-28', 'patient_phone': '01042877328'}
{'patient_id': 773, 'patient_name': '이승현', 'patient_sex': '남자', 'patient_birth': '2000-05-15', 'patient_phone': '01012091935'}
{'patient_id': 987, 'patient_name': '박유진', 'patient_sex': '여자', 'patient_birth': '1956-09-29', 'patient_phone': '0102116986'}
{'patient_id': 182, 'patient_name': '박상호', 'patient_sex': '남자', 'patient_birth': '1985-07-12', 'patient_phone': '01030112842'}
{'patient_id': 211, 'patient_name': '이순자', 'patient_sex': '여자', 'patient_birth': '2004-07-16', 'patient_phone': '01099065039'}
{'patient_id': 363, 'patient_name': '류경수', 'patient_sex': '여자', 'patient_birth': '1957-08-30', 'patient_phone': '01065906861'}
{'patient_id': 516, 'patient_name': '송미경', 'patient_sex': '여자', 'patient_birth': '1940-11-16', 'patient_phone': '01052637650'}
{'patient_id': 144, 'patient_name': '이민서', 'patient_sex': '남자', 'patient_birth': '1962-04-25', 'patient_phone': '01032573687'}
{'patient_id': 340, 'patient_name': '김은정', 'patient_sex': '여자', 'patient_birth': '1963-09-29', 'patient_phone': '0101444169'}
{'patient_id': 100, 'patient_name': '박지영', 'patient_sex': '여자', 'patient_birth': '1979-08-01', 'patient_phone': '01073797019'}
{'patient_id': 112, 'patient_name': '이예준', 'patient_sex': '여자', 'patient_birth': '1945-10-30', 'patient_phone': '01055378477'}
{'patient_id': 758, 'patient_name': '장지후', 'patient_sex': '남자', 'patient_birth': '1965-10-18', 'patient_phone': '01060221946'}
{'patient_id': 450, 'patient_name': '주성현', 'patient_sex': '남자', 'patient_birth': '1998-06-16', 'patient_phone': '01031009969'}
{'patient_id': 892, 'patient_name': '최현우', 'patient_sex': '여자', 'patient_birth': '1966-04-13', 'patient_phone': '01053083106'}
{'patient_id': 850, 'patient_name': '장성수', 'patient_sex': '남자', 'patient_birth': '1965-08-13', 'patient_phone': '01035261959'}
{'patient_id': 538, 'patient_name': '송준서', 'patient_sex': '여자', 'patient_birth': '1941-02-22', 'patient_phone': '01078231187'}
{'patient_id': 327, 'patient_name': '이진호', 'patient_sex': '여자', 'patient_birth': '1941-10-27', 'patient_phone': '01066781031'}
{'patient_id': 359, 'patient_name': '백경숙', 'patient_sex': '여자', 'patient_birth': '1983-03-23', 'patient_phone': '01012842526'}
{'patient_id': 125, 'patient_name': '백민서', 'patient_sex': '여자', 'patient_birth': '1999-11-20', 'patient_phone': '01033315966'}
{'patient_id': 626, 'patient_name': '최성훈', 'patient_sex': '여자', 'patient_birth': '1986-12-05', 'patient_phone': '01050190072'}
{'patient_id': 350, 'patient_name': '이지은', 'patient_sex': '여자', 'patient_birth': '1991-11-02', 'patient_phone': '01068939178'}
{'patient_id': 310, 'patient_name': '권춘자', 'patient_sex': '남자', 'patient_birth': '1984-01-21', 'patient_phone': '01090856822'}
{'patient_id': 899, 'patient_name': '박하은', 'patient_sex': '남자', 'patient_birth': '1986-05-04', 'patient_phone': '01079054027'}
{'patient_id': 605, 'patient_name': '김건우', 'patient_sex': '여자', 'patient_birth': '1990-01-21', 'patient_phone': '01011112462'}
{'patient_id': 668, 'patient_name': '이영수', 'patient_sex': '남자', 'patient_birth': '1949-04-23', 'patient_phone': '0107939690'}
{'patient_id': 116, 'patient_name': '이정호', 'patient_sex': '여자', 'patient_birth': '1947-02-02', 'patient_phone': '01046892773'}
{'patient_id': 952, 'patient_name': '김미경', 'patient_sex': '남자', 'patient_birth': '1968-05-08', 'patient_phone': '01052320158'}
{'patient_id': 291, 'patient_name': '김지원', 'patient_sex': '남자', 'patient_birth': '1952-06-13', 'patient_phone': '01093485042'}
{'patient_id': 823, 'patient_name': '이영길', 'patient_sex': '남자', 'patient_birth': '1987-09-12', 'patient_phone': '01083803417'}
{'patient_id': 877, 'patient_name': '이지민', 'patient_sex': '여자', 'patient_birth': '1984-01-06', 'patient_phone': '01044220704'}
{'patient_id': 975, 'patient_name': '고서준', 'patient_sex': '남자', 'patient_birth': '1948-10-08', 'patient_phone': '01056474004'}
{'patient_id': 54, 'patient_name': '이예준', 'patient_sex': '남자', 'patient_birth': '1980-02-12', 'patient_phone': '01029648786'}
{'patient_id': 379, 'patient_name': '이하윤', 'patient_sex': '여자', 'patient_birth': '1961-09-09', 'patient_phone': '01016987916'}
{'patient_id': 30, 'patient_name': '김민수', 'patient_sex': '남자', 'patient_birth': '1986-05-04', 'patient_phone': '01085494033'}
{'patient_id': 195, 'patient_name': '김은주', 'patient_sex': '남자', 'patient_birth': '1933-04-14', 'patient_phone': '01043709394'}
{'patient_id': 120, 'patient_name': '김민서', 'patient_sex': '여자', 'patient_birth': '1956-09-28', 'patient_phone': '01031383898'}
{'patient_id': 291, 'patient_name': '김서현', 'patient_sex': '여자', 'patient_birth': '1974-07-27', 'patient_phone': '01048028344'}
{'patient_id': 724, 'patient_name': '이예진', 'patient_sex': '남자', 'patient_birth': '1953-10-21', 'patient_phone': '01043108733'}
{'patient_id': 61, 'patient_name': '최미숙', 'patient_sex': '여자', 'patient_birth': '1966-08-21', 'patient_phone': '0108375844'}
{'patient_id': 926, 'patient_name': '강미경', 'patient_sex': '여자', 'patient_birth': '1999-12-05', 'patient_phone': '01040029876'}
{'patient_id': 35, 'patient_name': '서도현', 'patient_sex': '남자', 'patient_birth': '1971-10-09', 'patient_phone': '01097144045'}
{'patient_id': 173, 'patient_name': '신서준', 'patient_sex': '여자', 'patient_birth': '1998-06-17', 'patient_phone': '01095405731'}
{'patient_id': 323, 'patient_name': '황준호', 'patient_sex': '여자', 'patient_birth': '1957-03-20', 'patient_phone': '01013158453'}
{'patient_id': 951, 'patient_name': '손명자', 'patient_sex': '여자', 'patient_birth': '1941-12-10', 'patient_phone': '01063283731'}
{'patient_id': 116, 'patient_name': '이광수', 'patient_sex': '여자', 'patient_birth': '1985-07-26', 'patient_phone': '010821063'}
{'patient_id': 945, 'patient_name': '민수진', 'patient_sex': '여자', 'patient_birth': '1986-11-19', 'patient_phone': '01049575778'}
{'patient_id': 206, 'patient_name': '장진우', 'patient_sex': '남자', 'patient_birth': '1936-01-20', 'patient_phone': '01059077208'}
{'patient_id': 372, 'patient_name': '정영미', 'patient_sex': '남자', 'patient_birth': '1944-11-27', 'patient_phone': '01069285371'}
{'patient_id': 534, 'patient_name': '김병철', 'patient_sex': '남자', 'patient_birth': '1954-06-10', 'patient_phone': '01062848806'}
{'patient_id': 973, 'patient_name': '김현우', 'patient_sex': '남자', 'patient_birth': '1998-05-11', 'patient_phone': '01030196346'}
{'patient_id': 404, 'patient_name': '안은영', 'patient_sex': '여자', 'patient_birth': '1975-07-07', 'patient_phone': '01012286611'}
{'patient_id': 946, 'patient_name': '김정웅', 'patient_sex': '여자', 'patient_birth': '1967-10-02', 'patient_phone': '01055489334'}
{'patient_id': 315, 'patient_name': '김아름', 'patient_sex': '남자', 'patient_birth': '1966-07-23', 'patient_phone': '01071558477'}
{'patient_id': 812, 'patient_name': '김상철', 'patient_sex': '여자', 'patient_birth': '1974-07-22', 'patient_phone': '01068607576'}
{'patient_id': 744, 'patient_name': '이미정', 'patient_sex': '여자', 'patient_birth': '1975-02-25', 'patient_phone': '01091858847'}
{'patient_id': 385, 'patient_name': '김건우', 'patient_sex': '남자', 'patient_birth': '1947-10-15', 'patient_phone': '01099232823'}
{'patient_id': 603, 'patient_name': '서경숙', 'patient_sex': '여자', 'patient_birth': '1970-09-26', 'patient_phone': '01059024161'}
{'patient_id': 885, 'patient_name': '김승현', 'patient_sex': '여자', 'patient_birth': '1993-01-03', 'patient_phone': '0103686080'}
{'patient_id': 41, 'patient_name': '김민서', 'patient_sex': '여자', 'patient_birth': '1998-09-03', 'patient_phone': '01079391204'}
{'patient_id': 850, 'patient_name': '김준혁', 'patient_sex': '남자', 'patient_birth': '2000-02-14', 'patient_phone': '01010645425'}
{'patient_id': 362, 'patient_name': '손미숙', 'patient_sex': '여자', 'patient_birth': '1980-11-30', 'patient_phone': '01072500747'}
{'patient_id': 414, 'patient_name': '이정식', 'patient_sex': '여자', 'patient_birth': '1992-05-22', 'patient_phone': '01050154917'}
{'patient_id': 690, 'patient_name': '문정숙', 'patient_sex': '여자', 'patient_birth': '1953-04-18', 'patient_phone': '01050799017'}
{'patient_id': 862, 'patient_name': '황명자', 'patient_sex': '남자', 'patient_birth': '1963-07-15', 'patient_phone': '01011727522'}
{'patient_id': 190, 'patient_name': '최현준', 'patient_sex': '여자', 'patient_birth': '1960-06-20', 'patient_phone': '01073465741'}
{'patient_id': 555, 'patient_name': '이미숙', 'patient_sex': '남자', 'patient_birth': '1967-01-02', 'patient_phone': '01044410076'}
{'patient_id': 435, 'patient_name': '이현주', 'patient_sex': '여자', 'patient_birth': '1935-09-20', 'patient_phone': '01099326018'}
{'patient_id': 792, 'patient_name': '강서준', 'patient_sex': '남자', 'patient_birth': '1944-07-11', 'patient_phone': '01092071725'}
{'patient_id': 187, 'patient_name': '윤예준', 'patient_sex': '여자', 'patient_birth': '1974-08-18', 'patient_phone': '01082544071'}
{'patient_id': 135, 'patient_name': '김영미', 'patient_sex': '남자', 'patient_birth': '2004-03-09', 'patient_phone': '01093095549'}
{'patient_id': 627, 'patient_name': '김민재', 'patient_sex': '여자', 'patient_birth': '2004-07-11', 'patient_phone': '01041605872'}
{'patient_id': 691, 'patient_name': '박예은', 'patient_sex': '남자', 'patient_birth': '1935-11-26', 'patient_phone': '01020989302'}
{'patient_id': 460, 'patient_name': '박미정', 'patient_sex': '남자', 'patient_birth': '1962-08-21', 'patient_phone': '01074902646'}
{'patient_id': 488, 'patient_name': '김정자', 'patient_sex': '남자', 'patient_birth': '1984-07-06', 'patient_phone': '01025084763'}
{'patient_id': 360, 'patient_name': '이준영', 'patient_sex': '여자', 'patient_birth': '1945-07-05', 'patient_phone': '01049747734'}
{'patient_id': 468, 'patient_name': '김영일', 'patient_sex': '남자', 'patient_birth': '1954-07-25', 'patient_phone': '01088855415'}
{'patient_id': 181, 'patient_name': '안정희', 'patient_sex': '여자', 'patient_birth': '1988-11-16', 'patient_phone': '01071284963'}
{'patient_id': 884, 'patient_name': '강예준', 'patient_sex': '남자', 'patient_birth': '1981-04-25', 'patient_phone': '01076206854'}
{'patient_id': 323, 'patient_name': '윤상철', 'patient_sex': '여자', 'patient_birth': '1962-12-18', 'patient_phone': '0106652033'}
{'patient_id': 91, 'patient_name': '이민재', 'patient_sex': '여자', 'patient_birth': '1961-06-07', 'patient_phone': '01037888241'}
{'patient_id': 908, 'patient_name': '박하은', 'patient_sex': '남자', 'patient_birth': '1943-08-23', 'patient_phone': '01054101367'}
{'patient_id': 222, 'patient_name': '최경희', 'patient_sex': '남자', 'patient_birth': '1964-05-20', 'patient_phone': '01010580017'}
{'patient_id': 216, 'patient_name': '김영자', 'patient_sex': '남자', 'patient_birth': '1995-11-22', 'patient_phone': '01030117023'}
{'patient_id': 29, 'patient_name': '장준혁', 'patient_sex': '여자', 'patient_birth': '1939-04-24', 'patient_phone': '01024594619'}
{'patient_id': 238, 'patient_name': '이예진', 'patient_sex': '남자', 'patient_birth': '1938-10-05', 'patient_phone': '01064328642'}
{'patient_id': 308, 'patient_name': '황춘자', 'patient_sex': '남자', 'patient_birth': '1958-01-21', 'patient_phone': '01094465283'}
{'patient_id': 195, 'patient_name': '강아름', 'patient_sex': '여자', 'patient_birth': '1965-01-26', 'patient_phone': '01088143121'}
{'patient_id': 480, 'patient_name': '김옥자', 'patient_sex': '남자', 'patient_birth': '1945-05-19', 'patient_phone': '01078760335'}

**소아 환자 더미데이터**

In [137]:
from faker import Faker
import random

fake = Faker('ko_KR')

# 가짜 환자 데이터 생성
def generate_fake_patient():
    id = random.randint(1001, 1100)
    name = fake.name()
    sex = random.choice(['남자', '여자'])
    birthday = fake.date_of_birth(minimum_age=1, maximum_age=7)
    formatted_birthday = birthday.strftime('%Y-%m-%d')
    phone = '010' + str(fake.random_number(digits=8))

    return {
        'patient_id': id,
        'patient_name': name,
        'patient_sex': sex,
        'patient_birth': formatted_birthday,
        'patient_phone': phone,
    }

# 20개의 가짜 환자 데이터 생성
fake_patient_data2 = [generate_fake_patient() for _ in range(10)]
for patient in fake_patient_data2:
    print(patient)

{'patient_id': 1020, 'patient_name': '이정희', 'patient_sex': '남자', 'patient_birth': '2022-12-04', 'patient_phone': '01048978349'}
{'patient_id': 1009, 'patient_name': '김재현', 'patient_sex': '남자', 'patient_birth': '2017-01-02', 'patient_phone': '01046615888'}
{'patient_id': 1082, 'patient_name': '이보람', 'patient_sex': '여자', 'patient_birth': '2022-03-23', 'patient_phone': '01019773160'}
{'patient_id': 1084, 'patient_name': '박현우', 'patient_sex': '남자', 'patient_birth': '2018-08-26', 'patient_phone': '01078454084'}
{'patient_id': 1083, 'patient_name': '박현준', 'patient_sex': '남자', 'patient_birth': '2016-04-06', 'patient_phone': '01018650853'}
{'patient_id': 1024, 'patient_name': '최은주', 'patient_sex': '여자', 'patient_birth': '2017-05-02', 'patient_phone': '01065681627'}
{'patient_id': 1089, 'patient_name': '문영자', 'patient_sex': '남자', 'patient_birth': '2019-05-07', 'patient_phone': '01013270748'}
{'patient_id': 1015, 'patient_name': '허시우', 'patient_sex': '여자', 'patient_birth': '2022-07-14', 'patient_phone': '01026035763'}
{'patient_id': 1001, 'patient_name': '김현우', 'patient_sex': '남자', 'patient_birth': '2018-05-09', 'patient_phone': '01012511917'}
{'patient_id': 1092, 'patient_name': '박성수', 'patient_sex': '여자', 'patient_birth': '2019-08-30', 'patient_phone': '01046077614'}

In [138]:
fake_patient_data1 = pd.DataFrame(fake_patient_data1)
fake_patient_data2 = pd.DataFrame(fake_patient_data2)

In [139]:
import pandas as pd

merged_data = pd.concat([fake_patient_data1, fake_patient_data2], ignore_index=True)
print(merged_data)

    patient_id patient_name patient_sex patient_birth patient_phone
0           64          최영길          남자    1941-07-20    0104968477
1          721          백정남          여자    1993-01-20    0108497486
2          817          최지혜          남자    1986-07-28   01042877328
3          773          이승현          남자    2000-05-15   01012091935
4          987          박유진          여자    1956-09-29    0102116986
..         ...          ...         ...           ...           ...
95        1024          최은주          여자    2017-05-02   01065681627
96        1089          문영자          남자    2019-05-07   01013270748
97        1015          허시우          여자    2022-07-14   01026035763
98        1001          김현우          남자    2018-05-09   01012511917
99        1092          박성수          여자    2019-08-30   01046077614

[100 rows x 5 columns]

In [140]:
# Pandas DataFrame 생성
patient = pd.DataFrame(merged_data)
# CSV 파일로 저장
patient.to_csv('patients.csv', index=False, encoding='euckr')
print(patient.head(),'\n')
print(patient.tail())

   patient_id patient_name patient_sex patient_birth patient_phone
0          64          최영길          남자    1941-07-20    0104968477
1         721          백정남          여자    1993-01-20    0108497486
2         817          최지혜          남자    1986-07-28   01042877328
3         773          이승현          남자    2000-05-15   01012091935
4         987          박유진          여자    1956-09-29    0102116986

    patient_id patient_name patient_sex patient_birth patient_phone
95        1024          최은주          여자    2017-05-02   01065681627
96        1089          문영자          남자    2019-05-07   01013270748
97        1015          허시우          여자    2022-07-14   01026035763
98        1001          김현우          남자    2018-05-09   01012511917
99        1092          박성수          여자    2019-08-30   01046077614

### 의사 데이터

In [41]:
from faker import Faker
import random
fake = Faker('ko_KR')

def generate_fake_patient():
    id = random.randint(1, 1000)
    name = fake.name()
    birthday = fake.date_of_birth(minimum_age=18, maximum_age=90)
    formatted_birthday = birthday.strftime('%Y-%m-%d')
    phone = '010' + str(fake.random_number(digits=8))
    email = fake.email()

    return {
        'doctor_id': id,
        'doctor_birth': formatted_birthday,
        'doctor_phone': phone,
        'doctor_email' : email
    }

fake_doctor_data = [generate_fake_patient() for _ in range(203)]
for doctor in fake_doctor_data:
    print(doctor)

{'doctor_id': 442, 'doctor_birth': '1992-02-15', 'doctor_phone': '01067676112', 'doctor_email': 'ijunyeong@example.com'}
{'doctor_id': 988, 'doctor_birth': '1933-11-18', 'doctor_phone': '01023597980', 'doctor_email': 'dhan@example.com'}
{'doctor_id': 925, 'doctor_birth': '1979-10-27', 'doctor_phone': '01092075458', 'doctor_email': 'myeongsug39@example.com'}
{'doctor_id': 361, 'doctor_birth': '1961-08-12', 'doctor_phone': '01053401653', 'doctor_email': 'migyeong51@example.org'}
{'doctor_id': 404, 'doctor_birth': '1986-02-16', 'doctor_phone': '01075289462', 'doctor_email': 'yeweon90@example.com'}
{'doctor_id': 346, 'doctor_birth': '1983-08-20', 'doctor_phone': '01048689646', 'doctor_email': 'doyunbag@example.net'}
{'doctor_id': 800, 'doctor_birth': '2000-09-12', 'doctor_phone': '01013379886', 'doctor_email': 'wi@example.net'}
{'doctor_id': 178, 'doctor_birth': '1964-07-28', 'doctor_phone': '01061509982', 'doctor_email': 'lan@example.com'}
{'doctor_id': 663, 'doctor_birth': '1990-06-05', 'doctor_phone': '01017920359', 'doctor_email': 'coemiyeong@example.com'}
{'doctor_id': 887, 'doctor_birth': '1940-05-08', 'doctor_phone': '01080677915', 'doctor_email': 'hongujin@example.com'}
{'doctor_id': 920, 'doctor_birth': '1980-10-03', 'doctor_phone': '01079726158', 'doctor_email': 'minsugim@example.com'}
{'doctor_id': 236, 'doctor_birth': '1973-08-29', 'doctor_phone': '01028510976', 'doctor_email': 'fi@example.com'}
{'doctor_id': 169, 'doctor_birth': '1942-12-06', 'doctor_phone': '01049458780', 'doctor_email': 'jiyeong57@example.net'}
{'doctor_id': 109, 'doctor_birth': '1976-03-31', 'doctor_phone': '01026654932', 'doctor_email': 'jeongja27@example.net'}
{'doctor_id': 391, 'doctor_birth': '1944-01-24', 'doctor_phone': '01030195617', 'doctor_email': 'hyeonjugang@example.com'}
{'doctor_id': 860, 'doctor_birth': '1993-05-31', 'doctor_phone': '0102455403', 'doctor_email': 'baggyeongsug@example.com'}
{'doctor_id': 906, 'doctor_birth': '1943-08-29', 'doctor_phone': '01012022293', 'doctor_email': 'rgim@example.net'}
{'doctor_id': 87, 'doctor_birth': '1985-05-25', 'doctor_phone': '0103841988', 'doctor_email': 'jingwangsu@example.net'}
{'doctor_id': 375, 'doctor_birth': '1954-09-23', 'doctor_phone': '01084389654', 'doctor_email': 'oha@example.net'}
{'doctor_id': 78, 'doctor_birth': '1940-02-18', 'doctor_phone': '01044380438', 'doctor_email': 'miyeongi@example.com'}
{'doctor_id': 109, 'doctor_birth': '1935-09-11', 'doctor_phone': '01020306961', 'doctor_email': 'jiweon04@example.net'}
{'doctor_id': 81, 'doctor_birth': '1981-03-12', 'doctor_phone': '01031233344', 'doctor_email': 'iyeongsun@example.org'}
{'doctor_id': 329, 'doctor_birth': '1959-03-04', 'doctor_phone': '01078562287', 'doctor_email': 'jieun46@example.com'}
{'doctor_id': 208, 'doctor_birth': '1952-04-23', 'doctor_phone': '01016020811', 'doctor_email': 'eunjeong65@example.com'}
{'doctor_id': 364, 'doctor_birth': '1935-02-24', 'doctor_phone': '01049133915', 'doctor_email': 'jongsu78@example.net'}
{'doctor_id': 246, 'doctor_birth': '1961-10-14', 'doctor_phone': '01013652323', 'doctor_email': 'yeonghyi45@example.net'}
{'doctor_id': 123, 'doctor_birth': '1970-11-25', 'doctor_phone': '01090882074', 'doctor_email': 'yejiha@example.net'}
{'doctor_id': 919, 'doctor_birth': '1971-01-26', 'doctor_phone': '01066401972', 'doctor_email': 'jihungweon@example.org'}
{'doctor_id': 42, 'doctor_birth': '1992-08-13', 'doctor_phone': '01061704524', 'doctor_email': 'eunseoi@example.com'}
{'doctor_id': 265, 'doctor_birth': '1947-09-12', 'doctor_phone': '01082433859', 'doctor_email': 'vgim@example.com'}
{'doctor_id': 859, 'doctor_birth': '1954-05-12', 'doctor_phone': '01033719860', 'doctor_email': 'zi@example.net'}
{'doctor_id': 378, 'doctor_birth': '1959-05-13', 'doctor_phone': '01066179553', 'doctor_email': 'boram58@example.net'}
{'doctor_id': 276, 'doctor_birth': '1985-10-29', 'doctor_phone': '01049747149', 'doctor_email': 'gbag@example.org'}
{'doctor_id': 803, 'doctor_birth': '1978-01-03', 'doctor_phone': '0107049066', 'doctor_email': 'gimjimin@example.org'}
{'doctor_id': 168, 'doctor_birth': '1997-11-06', 'doctor_phone': '01022186923', 'doctor_email': 'xju@example.org'}
{'doctor_id': 827, 'doctor_birth': '1934-11-18', 'doctor_phone': '01092281900', 'doctor_email': 'minji14@example.org'}
{'doctor_id': 869, 'doctor_birth': '1976-01-03', 'doctor_phone': '01097010877', 'doctor_email': 'heogyeongsug@example.net'}
{'doctor_id': 404, 'doctor_birth': '1980-09-23', 'doctor_phone': '01039352781', 'doctor_email': 'hongjiweon@example.com'}
{'doctor_id': 932, 'doctor_birth': '2003-04-28', 'doctor_phone': '01051211381', 'doctor_email': 'seohyeon71@example.com'}
{'doctor_id': 440, 'doctor_birth': '1956-12-16', 'doctor_phone': '01092517280', 'doctor_email': 'mi@example.org'}
{'doctor_id': 843, 'doctor_birth': '1938-06-07', 'doctor_phone': '01026639848', 'doctor_email': 'lgim@example.com'}
{'doctor_id': 854, 'doctor_birth': '1961-07-17', 'doctor_phone': '01036810685', 'doctor_email': 'gangyunseo@example.org'}
{'doctor_id': 166, 'doctor_birth': '2005-08-20', 'doctor_phone': '01034342413', 'doctor_email': 'gyeongsu84@example.org'}
{'doctor_id': 74, 'doctor_birth': '1963-05-09', 'doctor_phone': '01075236866', 'doctor_email': 'misugmun@example.org'}
{'doctor_id': 259, 'doctor_birth': '1943-12-03', 'doctor_phone': '01092963243', 'doctor_email': 'gimogja@example.com'}
{'doctor_id': 450, 'doctor_birth': '1940-10-12', 'doctor_phone': '01068004908', 'doctor_email': 'yeongsig63@example.net'}
{'doctor_id': 922, 'doctor_birth': '1954-04-06', 'doctor_phone': '01020172688', 'doctor_email': 'sanghoi@example.org'}
{'doctor_id': 162, 'doctor_birth': '1954-10-06', 'doctor_phone': '01028098169', 'doctor_email': 'ijihyeon@example.com'}
{'doctor_id': 947, 'doctor_birth': '2004-01-24', 'doctor_phone': '01038643852', 'doctor_email': 'junho07@example.com'}
{'doctor_id': 458, 'doctor_birth': '1964-09-13', 'doctor_phone': '01067425094', 'doctor_email': 'icaeweon@example.net'}
{'doctor_id': 689, 'doctor_birth': '1973-08-14', 'doctor_phone': '01011508131', 'doctor_email': 'seoyeon17@example.com'}
{'doctor_id': 243, 'doctor_birth': '1990-08-07', 'doctor_phone': '01050615328', 'doctor_email': 'noyeongsun@example.net'}
{'doctor_id': 283, 'doctor_birth': '1940-09-19', 'doctor_phone': '01050560994', 'doctor_email': 'pbaeg@example.org'}
{'doctor_id': 574, 'doctor_birth': '1961-08-18', 'doctor_phone': '01022069071', 'doctor_email': 'hwangyeongsig@example.net'}
{'doctor_id': 863, 'doctor_birth': '1981-01-28', 'doctor_phone': '01014229366', 'doctor_email': 'sunoggim@example.net'}
{'doctor_id': 594, 'doctor_birth': '1938-11-08', 'doctor_phone': '01067481667', 'doctor_email': 'ryun@example.org'}
{'doctor_id': 748, 'doctor_birth': '1940-04-19', 'doctor_phone': '01022605342', 'doctor_email': 'jiyeon99@example.org'}
{'doctor_id': 352, 'doctor_birth': '1963-10-31', 'doctor_phone': '01062112136', 'doctor_email': 'caeweonjang@example.org'}
{'doctor_id': 662, 'doctor_birth': '2001-01-10', 'doctor_phone': '01031214712', 'doctor_email': 'ieunju@example.org'}
{'doctor_id': 700, 'doctor_birth': '1933-04-04', 'doctor_phone': '01083108272', 'doctor_email': 'ji@example.com'}
{'doctor_id': 137, 'doctor_birth': '1963-07-23', 'doctor_phone': '01052117086', 'doctor_email': 'gyeongsug43@example.org'}
{'doctor_id': 872, 'doctor_birth': '1957-05-10', 'doctor_phone': '01030070170', 'doctor_email': 'lgim@example.com'}
{'doctor_id': 591, 'doctor_birth': '1968-09-10', 'doctor_phone': '01063342326', 'doctor_email': 'dohyeon77@example.net'}
{'doctor_id': 969, 'doctor_birth': '1981-12-29', 'doctor_phone': '01095445936', 'doctor_email': 'ganggyeongja@example.com'}
{'doctor_id': 815, 'doctor_birth': '1937-10-03', 'doctor_phone': '01064524539', 'doctor_email': 'ogja90@example.org'}
{'doctor_id': 531, 'doctor_birth': '1967-06-27', 'doctor_phone': '01020115170', 'doctor_email': 'yunyeongja@example.org'}
{'doctor_id': 783, 'doctor_birth': '1960-02-11', 'doctor_phone': '01047205774', 'doctor_email': 'ygim@example.net'}
{'doctor_id': 808, 'doctor_birth': '1969-01-14', 'doctor_phone': '0101663597', 'doctor_email': 'imhaeun@example.org'}
{'doctor_id': 703, 'doctor_birth': '1953-05-31', 'doctor_phone': '01091306782', 'doctor_email': 'jiyeonseo@example.com'}
{'doctor_id': 984, 'doctor_birth': '1968-08-20', 'doctor_phone': '01017473044', 'doctor_email': 'ryuareum@example.org'}
{'doctor_id': 409, 'doctor_birth': '1985-10-17', 'doctor_phone': '01027725210', 'doctor_email': 'gimdoyun@example.com'}
{'doctor_id': 577, 'doctor_birth': '1988-05-23', 'doctor_phone': '0105906402', 'doctor_email': 'cgim@example.com'}
{'doctor_id': 934, 'doctor_birth': '1987-02-15', 'doctor_phone': '01069489878', 'doctor_email': 'mijeong44@example.com'}
{'doctor_id': 88, 'doctor_birth': '1953-10-26', 'doctor_phone': '01049957586', 'doctor_email': 'ihyeonsug@example.net'}
{'doctor_id': 509, 'doctor_birth': '1959-08-03', 'doctor_phone': '01054556372', 'doctor_email': 'mheo@example.com'}
{'doctor_id': 223, 'doctor_birth': '1975-03-14', 'doctor_phone': '0108180647', 'doctor_email': 'doyun19@example.org'}
{'doctor_id': 544, 'doctor_birth': '1941-01-16', 'doctor_phone': '01066458326', 'doctor_email': 'sujin08@example.org'}
{'doctor_id': 733, 'doctor_birth': '2000-11-01', 'doctor_phone': '01086789634', 'doctor_email': 'hno@example.net'}
{'doctor_id': 777, 'doctor_birth': '1969-06-30', 'doctor_phone': '01058532687', 'doctor_email': 'jihuni@example.net'}
{'doctor_id': 988, 'doctor_birth': '1951-07-17', 'doctor_phone': '01011052000', 'doctor_email': 'jeongho06@example.org'}
{'doctor_id': 735, 'doctor_birth': '1986-11-07', 'doctor_phone': '01042832175', 'doctor_email': 'dgim@example.org'}
{'doctor_id': 173, 'doctor_birth': '1993-11-27', 'doctor_phone': '01054349232', 'doctor_email': 'sanghyeongim@example.com'}
{'doctor_id': 334, 'doctor_birth': '2005-07-11', 'doctor_phone': '01015943424', 'doctor_email': 'yejibag@example.com'}
{'doctor_id': 642, 'doctor_birth': '1997-01-18', 'doctor_phone': '01037676390', 'doctor_email': 'minji17@example.net'}
{'doctor_id': 363, 'doctor_birth': '1968-08-14', 'doctor_phone': '01050274286', 'doctor_email': 'yeonggil14@example.org'}
{'doctor_id': 207, 'doctor_birth': '1989-06-30', 'doctor_phone': '01031121447', 'doctor_email': 'bagmiyeong@example.com'}
{'doctor_id': 158, 'doctor_birth': '1948-08-06', 'doctor_phone': '01098521480', 'doctor_email': 'zcoe@example.org'}
{'doctor_id': 710, 'doctor_birth': '1948-07-22', 'doctor_phone': '01031374571', 'doctor_email': 'gimjihye@example.org'}
{'doctor_id': 321, 'doctor_birth': '1945-11-23', 'doctor_phone': '0107135956', 'doctor_email': 'ni@example.com'}
{'doctor_id': 777, 'doctor_birth': '1983-11-12', 'doctor_phone': '01054661921', 'doctor_email': 'jiugim@example.net'}
{'doctor_id': 724, 'doctor_birth': '1971-04-01', 'doctor_phone': '01079356429', 'doctor_email': 'yujin00@example.org'}
{'doctor_id': 394, 'doctor_birth': '1981-04-25', 'doctor_phone': '01089099884', 'doctor_email': 'jihyeongim@example.net'}
{'doctor_id': 601, 'doctor_birth': '1945-02-12', 'doctor_phone': '0107620673', 'doctor_email': 'seohyeon73@example.org'}
{'doctor_id': 165, 'doctor_birth': '1933-04-13', 'doctor_phone': '01020009285', 'doctor_email': 'coejaeho@example.com'}
{'doctor_id': 834, 'doctor_birth': '1985-02-10', 'doctor_phone': '01092181692', 'doctor_email': 'hyeonu75@example.net'}
{'doctor_id': 976, 'doctor_birth': '1947-09-17', 'doctor_phone': '01099816362', 'doctor_email': 'gimogsun@example.com'}
{'doctor_id': 501, 'doctor_birth': '1953-09-13', 'doctor_phone': '0105687056', 'doctor_email': 'bgang@example.com'}
{'doctor_id': 622, 'doctor_birth': '1997-05-22', 'doctor_phone': '01066687603', 'doctor_email': 'jiweoni@example.net'}
{'doctor_id': 36, 'doctor_birth': '1947-10-16', 'doctor_phone': '01055811513', 'doctor_email': 'jeongsuggweon@example.com'}
{'doctor_id': 978, 'doctor_birth': '1999-10-31', 'doctor_phone': '01015004710', 'doctor_email': 'mgweon@example.org'}
{'doctor_id': 779, 'doctor_birth': '1976-01-22', 'doctor_phone': '01054236114', 'doctor_email': 'ahong@example.org'}
{'doctor_id': 718, 'doctor_birth': '1975-01-15', 'doctor_phone': '01026294535', 'doctor_email': 'vgim@example.com'}
{'doctor_id': 134, 'doctor_birth': '1977-04-30', 'doctor_phone': '01038771612', 'doctor_email': 'sumin54@example.org'}
{'doctor_id': 940, 'doctor_birth': '1993-10-10', 'doctor_phone': '01014398631', 'doctor_email': 'zgim@example.org'}
{'doctor_id': 275, 'doctor_birth': '1950-02-05', 'doctor_phone': '0101734074', 'doctor_email': 'baegseongsu@example.net'}
{'doctor_id': 931, 'doctor_birth': '1953-10-07', 'doctor_phone': '01068494488', 'doctor_email': 'minseogim@example.org'}
{'doctor_id': 877, 'doctor_birth': '1988-06-26', 'doctor_phone': '01010524743', 'doctor_email': 'ijunhyeog@example.org'}
{'doctor_id': 368, 'doctor_birth': '1948-03-16', 'doctor_phone': '01066010791', 'doctor_email': 'yeongho08@example.net'}
{'doctor_id': 542, 'doctor_birth': '1983-10-26', 'doctor_phone': '01012275125', 'doctor_email': 'siu45@example.net'}
{'doctor_id': 223, 'doctor_birth': '1934-03-29', 'doctor_phone': '01079798411', 'doctor_email': 'seongmin50@example.net'}
{'doctor_id': 580, 'doctor_birth': '1997-07-23', 'doctor_phone': '01031138490', 'doctor_email': 'qi@example.com'}
{'doctor_id': 229, 'doctor_birth': '1961-03-20', 'doctor_phone': '01071141333', 'doctor_email': 'seoyun92@example.com'}
{'doctor_id': 585, 'doctor_birth': '1968-01-15', 'doctor_phone': '01024304938', 'doctor_email': 'ji@example.com'}
{'doctor_id': 356, 'doctor_birth': '1949-04-03', 'doctor_phone': '01042137578', 'doctor_email': 'di@example.net'}
{'doctor_id': 1, 'doctor_birth': '1992-01-05', 'doctor_phone': '01045473582', 'doctor_email': 'fcoe@example.net'}
{'doctor_id': 427, 'doctor_birth': '1993-06-15', 'doctor_phone': '01010039312', 'doctor_email': 'gangcunja@example.org'}
{'doctor_id': 482, 'doctor_birth': '1946-12-27', 'doctor_phone': '01037411331', 'doctor_email': 'bagseongsu@example.com'}
{'doctor_id': 664, 'doctor_birth': '2004-06-25', 'doctor_phone': '01043431403', 'doctor_email': 'eunjunam@example.net'}
{'doctor_id': 846, 'doctor_birth': '1937-09-19', 'doctor_phone': '01075402756', 'doctor_email': 'ohan@example.net'}
{'doctor_id': 916, 'doctor_birth': '1940-12-29', 'doctor_phone': '01070829870', 'doctor_email': 'ijeongsun@example.com'}
{'doctor_id': 874, 'doctor_birth': '1943-07-11', 'doctor_phone': '01056100337', 'doctor_email': 'yeongja76@example.net'}
{'doctor_id': 946, 'doctor_birth': '2000-05-13', 'doctor_phone': '01047488862', 'doctor_email': 'yeonggil87@example.net'}
{'doctor_id': 448, 'doctor_birth': '1981-08-06', 'doctor_phone': '01023326209', 'doctor_email': 'baegseonyeong@example.org'}
{'doctor_id': 491, 'doctor_birth': '1998-03-20', 'doctor_phone': '01023167926', 'doctor_email': 'jihun87@example.net'}
{'doctor_id': 993, 'doctor_birth': '1999-03-24', 'doctor_phone': '01021232412', 'doctor_email': 'zi@example.com'}
{'doctor_id': 89, 'doctor_birth': '1998-12-23', 'doctor_phone': '01030302890', 'doctor_email': 'ai@example.com'}
{'doctor_id': 324, 'doctor_birth': '1934-06-29', 'doctor_phone': '01021512378', 'doctor_email': 'siu22@example.org'}
{'doctor_id': 651, 'doctor_birth': '1977-06-25', 'doctor_phone': '01016681050', 'doctor_email': 'yeongmi94@example.net'}
{'doctor_id': 346, 'doctor_birth': '1946-06-15', 'doctor_phone': '01047920787', 'doctor_email': 'mijeong42@example.net'}
{'doctor_id': 873, 'doctor_birth': '1948-11-04', 'doctor_phone': '01045225436', 'doctor_email': 'hyeonubag@example.org'}
{'doctor_id': 545, 'doctor_birth': '1967-05-20', 'doctor_phone': '01086614129', 'doctor_email': 'yeongceol17@example.org'}
{'doctor_id': 98, 'doctor_birth': '1995-06-16', 'doctor_phone': '01032702582', 'doctor_email': 'gimgyeongja@example.com'}
{'doctor_id': 959, 'doctor_birth': '1977-02-09', 'doctor_phone': '01076047364', 'doctor_email': 'seongho40@example.net'}
{'doctor_id': 692, 'doctor_birth': '1986-08-18', 'doctor_phone': '01090306085', 'doctor_email': 'seonyeonghan@example.com'}
{'doctor_id': 854, 'doctor_birth': '1998-08-08', 'doctor_phone': '01070000362', 'doctor_email': 'yeongmii@example.org'}
{'doctor_id': 337, 'doctor_birth': '1983-01-24', 'doctor_phone': '01012025889', 'doctor_email': 'icoe@example.net'}
{'doctor_id': 606, 'doctor_birth': '2003-06-04', 'doctor_phone': '01078588273', 'doctor_email': 'jiu55@example.org'}
{'doctor_id': 750, 'doctor_birth': '1986-09-25', 'doctor_phone': '01029505001', 'doctor_email': 'yeweon81@example.net'}
{'doctor_id': 865, 'doctor_birth': '1955-12-21', 'doctor_phone': '01083561922', 'doctor_email': 'mjang@example.org'}
{'doctor_id': 91, 'doctor_birth': '1982-03-08', 'doctor_phone': '01015303741', 'doctor_email': 'seunghyeon08@example.com'}
{'doctor_id': 785, 'doctor_birth': '1971-01-19', 'doctor_phone': '01054076934', 'doctor_email': 'gimjeongja@example.net'}
{'doctor_id': 103, 'doctor_birth': '1996-09-19', 'doctor_phone': '01012816261', 'doctor_email': 'rbaeg@example.com'}
{'doctor_id': 570, 'doctor_birth': '1969-04-23', 'doctor_phone': '01025566329', 'doctor_email': 'junseojo@example.com'}
{'doctor_id': 483, 'doctor_birth': '1934-12-29', 'doctor_phone': '01062348121', 'doctor_email': 'bagjunhyeog@example.net'}
{'doctor_id': 692, 'doctor_birth': '1991-12-07', 'doctor_phone': '01026221685', 'doctor_email': 'yunseogim@example.org'}
{'doctor_id': 583, 'doctor_birth': '1962-10-30', 'doctor_phone': '01065837486', 'doctor_email': 'wheo@example.com'}
{'doctor_id': 919, 'doctor_birth': '2001-01-04', 'doctor_phone': '01036063901', 'doctor_email': 'yunseo50@example.org'}
{'doctor_id': 610, 'doctor_birth': '1933-11-07', 'doctor_phone': '0106383071', 'doctor_email': 'baghayun@example.net'}
{'doctor_id': 894, 'doctor_birth': '1985-11-03', 'doctor_phone': '01063355466', 'doctor_email': 'gimyejin@example.net'}
{'doctor_id': 951, 'doctor_birth': '1945-09-19', 'doctor_phone': '01020854115', 'doctor_email': 'seojuneom@example.com'}
{'doctor_id': 380, 'doctor_birth': '1995-11-25', 'doctor_phone': '01094321594', 'doctor_email': 'chwang@example.com'}
{'doctor_id': 542, 'doctor_birth': '1933-04-01', 'doctor_phone': '01035324232', 'doctor_email': 'coeseohyeon@example.org'}
{'doctor_id': 481, 'doctor_birth': '1945-05-17', 'doctor_phone': '01049915158', 'doctor_email': 'dohyeon07@example.net'}
{'doctor_id': 285, 'doctor_birth': '1952-01-10', 'doctor_phone': '01097686079', 'doctor_email': 'wjang@example.net'}
{'doctor_id': 590, 'doctor_birth': '1987-09-19', 'doctor_phone': '01062723498', 'doctor_email': 'eunjeong30@example.net'}
{'doctor_id': 225, 'doctor_birth': '2000-04-19', 'doctor_phone': '01043867515', 'doctor_email': 'jiu19@example.net'}
{'doctor_id': 151, 'doctor_birth': '1957-11-28', 'doctor_phone': '01034582881', 'doctor_email': 'hsin@example.net'}
{'doctor_id': 859, 'doctor_birth': '1934-12-01', 'doctor_phone': '01075615800', 'doctor_email': 'yeongmi55@example.org'}
{'doctor_id': 960, 'doctor_birth': '1936-07-02', 'doctor_phone': '01057873708', 'doctor_email': 'myeongsug14@example.com'}
{'doctor_id': 715, 'doctor_birth': '2005-05-05', 'doctor_phone': '01018601043', 'doctor_email': 'gimdohyeon@example.net'}
{'doctor_id': 324, 'doctor_birth': '2002-03-03', 'doctor_phone': '01076444319', 'doctor_email': 'habyeongceol@example.org'}
{'doctor_id': 717, 'doctor_birth': '1938-02-22', 'doctor_phone': '01051873484', 'doctor_email': 'lju@example.com'}
{'doctor_id': 808, 'doctor_birth': '1964-04-07', 'doctor_phone': '0109633544', 'doctor_email': 'yunmyeongja@example.net'}
{'doctor_id': 485, 'doctor_birth': '1957-12-30', 'doctor_phone': '0104874741', 'doctor_email': 'eungyeongim@example.org'}
{'doctor_id': 90, 'doctor_birth': '1943-10-18', 'doctor_phone': '0108184594', 'doctor_email': 'yeongsunhong@example.org'}
{'doctor_id': 861, 'doctor_birth': '1981-11-30', 'doctor_phone': '01048662785', 'doctor_email': 'jihu74@example.com'}
{'doctor_id': 669, 'doctor_birth': '1999-11-17', 'doctor_phone': '01089224055', 'doctor_email': 'goseungmin@example.org'}

In [98]:
import pandas as pd
# Pandas DataFrame 생성
doctor_f = pd.DataFrame(fake_doctor_data)
# CSV 파일로 저장
doctor_f.to_csv('doctor_f.csv', index=False, encoding='euckr')

print(doctor_f.head(),'\n')
print(doctor_f.tail())

   doctor_id doctor_birth doctor_phone             doctor_email
0        442   1992-02-15  01067676112    ijunyeong@example.com
1        988   1933-11-18  01023597980         dhan@example.com
2        925   1979-10-27  01092075458  myeongsug39@example.com
3        361   1961-08-12  01053401653   migyeong51@example.org
4        404   1986-02-16  01075289462     yeweon90@example.com

     doctor_id doctor_birth doctor_phone             doctor_email
198        939   1938-06-12  01019047234   gimgwangsu@example.com
199        770   1954-08-01  01099854439         pgim@example.net
200        205   1945-01-01  01018072338      jinuson@example.net
201        410   1953-04-09  01088006824   gweoneunju@example.org
202        476   1942-08-28  01073918497  hongyeongil@example.net

**< 실제 데이터와 합친 최종 데이터 >**

In [61]:
# 최종 의사 데이터
doctors = pd.read_csv("doctors.csv")
doctors.head()

,doctor_id,field_id,doctor_name,specialized_field,doctor_birth,doctor_phone,doctor_email
0,442,1,정혜원,감염,1992-02-15,1067676112,ijunyeong@example.com
1,988,1,김희성,감염,1933-11-18,1023597980,dhan@example.com
2,925,1,김준형,감염,1979-10-27,1092075458,myeongsug39@example.com
3,361,2,오태근,"내분비계, 갑상선, 당뇨",1961-08-12,1053401653,migyeong51@example.org
4,404,2,전현정,"내분비계, 당뇨, 골다공증, 갑상선",1986-02-16,1075289462,yeweon90@example.com

In [62]:
doctors.head()

,doctor_id,field_id,doctor_name,specialized_field,doctor_birth,doctor_phone,doctor_email
0,442,1,정혜원,감염,1992-02-15,1067676112,ijunyeong@example.com
1,988,1,김희성,감염,1933-11-18,1023597980,dhan@example.com
2,925,1,김준형,감염,1979-10-27,1092075458,myeongsug39@example.com
3,361,2,오태근,"내분비계, 갑상선, 당뇨",1961-08-12,1053401653,migyeong51@example.org
4,404,2,전현정,"내분비계, 당뇨, 골다공증, 갑상선",1986-02-16,1075289462,yeweon90@example.com

### 질병 더미데이터

In [97]:
from faker import Faker
import random

fake = Faker('ko_KR')

# 질병 데이터 생성
def generate_fake_patient():
    id = random.randint(1, 1000)

    return {
        'disease_id': id,
    }

# 100개의 질병 데이터 생성
fake_disease_data = [generate_fake_patient() for _ in range(100)]

disease_id = pd.DataFrame(fake_disease_data)
disease_id.to_csv('disease_id.csv', index=False, encoding='euckr')

In [100]:
disease = pd.read_csv("diseases.csv")
disease.head()

   disease_id disease
0         852      감기
1         510      폐렴
2         824    요로감염
3         764    신부전증
4          65     신장염

### 진료내역 더미데이터

In [26]:
# 진료과 내역 데이터
field = pd.read_csv("fields.csv")
field.head()

   field_id majorfield minorfield
0         1         내과       감염내과
1         2         내과      내분비내과
2         3         내과     류마티스내과
3         4         내과      소화기내과
4         5         내과       신장내과

In [102]:
from faker import Faker
import random

fake = Faker('ko_KR')

# 가짜 진료내역 데이터 일부 칼럼 생성
def generate_fake_patient():
    id = random.randint(1, 1000)
    year = random.randint(2021, 2023)
    month = random.randint(1, 12)
    day = random.randint(1, 28)
    cost = random.randint(1000, 100000)

    return {
        'record_id': id,
        'record_year': year,
        'record_month': month,
        'record_day': day,
        'cost' : cost
    }

# 100개의 가짜 진료내역 데이터 생성 
fake_record_data = [generate_fake_patient() for _ in range(100)]

# 결과 출력
for record in fake_record_data:
    print(record)

{'record_id': 810, 'record_year': 2023, 'record_month': 7, 'record_day': 11, 'cost': 57323}
{'record_id': 749, 'record_year': 2022, 'record_month': 2, 'record_day': 10, 'cost': 24560}
{'record_id': 902, 'record_year': 2022, 'record_month': 2, 'record_day': 12, 'cost': 15703}
{'record_id': 490, 'record_year': 2022, 'record_month': 6, 'record_day': 15, 'cost': 59357}
{'record_id': 927, 'record_year': 2021, 'record_month': 3, 'record_day': 6, 'cost': 94293}
{'record_id': 113, 'record_year': 2023, 'record_month': 4, 'record_day': 15, 'cost': 1758}
{'record_id': 98, 'record_year': 2021, 'record_month': 12, 'record_day': 20, 'cost': 58498}
{'record_id': 42, 'record_year': 2023, 'record_month': 7, 'record_day': 21, 'cost': 82599}
{'record_id': 633, 'record_year': 2022, 'record_month': 3, 'record_day': 17, 'cost': 40644}
{'record_id': 776, 'record_year': 2022, 'record_month': 2, 'record_day': 4, 'cost': 51318}
{'record_id': 461, 'record_year': 2022, 'record_month': 11, 'record_day': 15, 'cost': 83348}
{'record_id': 511, 'record_year': 2021, 'record_month': 4, 'record_day': 2, 'cost': 79090}
{'record_id': 877, 'record_year': 2022, 'record_month': 6, 'record_day': 27, 'cost': 13212}
{'record_id': 738, 'record_year': 2021, 'record_month': 12, 'record_day': 1, 'cost': 82829}
{'record_id': 989, 'record_year': 2022, 'record_month': 3, 'record_day': 14, 'cost': 96406}
{'record_id': 506, 'record_year': 2023, 'record_month': 5, 'record_day': 10, 'cost': 60237}
{'record_id': 978, 'record_year': 2023, 'record_month': 10, 'record_day': 8, 'cost': 13589}
{'record_id': 823, 'record_year': 2023, 'record_month': 7, 'record_day': 22, 'cost': 19695}
{'record_id': 486, 'record_year': 2021, 'record_month': 6, 'record_day': 26, 'cost': 44003}
{'record_id': 813, 'record_year': 2021, 'record_month': 1, 'record_day': 12, 'cost': 45846}
{'record_id': 234, 'record_year': 2022, 'record_month': 8, 'record_day': 16, 'cost': 48214}
{'record_id': 223, 'record_year': 2023, 'record_month': 1, 'record_day': 13, 'cost': 72962}
{'record_id': 672, 'record_year': 2023, 'record_month': 3, 'record_day': 24, 'cost': 6364}
{'record_id': 773, 'record_year': 2021, 'record_month': 3, 'record_day': 18, 'cost': 61132}
{'record_id': 668, 'record_year': 2023, 'record_month': 11, 'record_day': 23, 'cost': 89029}
{'record_id': 350, 'record_year': 2023, 'record_month': 12, 'record_day': 14, 'cost': 86411}
{'record_id': 110, 'record_year': 2023, 'record_month': 5, 'record_day': 26, 'cost': 62203}
{'record_id': 168, 'record_year': 2023, 'record_month': 10, 'record_day': 2, 'cost': 17216}
{'record_id': 38, 'record_year': 2022, 'record_month': 12, 'record_day': 6, 'cost': 47407}
{'record_id': 228, 'record_year': 2022, 'record_month': 8, 'record_day': 3, 'cost': 49707}
{'record_id': 632, 'record_year': 2022, 'record_month': 4, 'record_day': 26, 'cost': 87491}
{'record_id': 302, 'record_year': 2022, 'record_month': 7, 'record_day': 9, 'cost': 95330}
{'record_id': 849, 'record_year': 2023, 'record_month': 1, 'record_day': 9, 'cost': 56945}
{'record_id': 535, 'record_year': 2022, 'record_month': 11, 'record_day': 6, 'cost': 75062}
{'record_id': 201, 'record_year': 2023, 'record_month': 3, 'record_day': 18, 'cost': 64251}
{'record_id': 924, 'record_year': 2022, 'record_month': 5, 'record_day': 2, 'cost': 79392}
{'record_id': 122, 'record_year': 2021, 'record_month': 12, 'record_day': 26, 'cost': 32442}
{'record_id': 699, 'record_year': 2021, 'record_month': 5, 'record_day': 14, 'cost': 77464}
{'record_id': 661, 'record_year': 2021, 'record_month': 1, 'record_day': 15, 'cost': 12269}
{'record_id': 906, 'record_year': 2021, 'record_month': 1, 'record_day': 4, 'cost': 1760}
{'record_id': 235, 'record_year': 2021, 'record_month': 6, 'record_day': 11, 'cost': 59689}
{'record_id': 603, 'record_year': 2023, 'record_month': 4, 'record_day': 3, 'cost': 53076}
{'record_id': 696, 'record_year': 2021, 'record_month': 12, 'record_day': 7, 'cost': 3772}
{'record_id': 423, 'record_year': 2022, 'record_month': 9, 'record_day': 23, 'cost': 9771}
{'record_id': 636, 'record_year': 2021, 'record_month': 3, 'record_day': 23, 'cost': 6710}
{'record_id': 497, 'record_year': 2021, 'record_month': 11, 'record_day': 28, 'cost': 19591}
{'record_id': 398, 'record_year': 2022, 'record_month': 9, 'record_day': 26, 'cost': 60509}
{'record_id': 152, 'record_year': 2023, 'record_month': 2, 'record_day': 3, 'cost': 79476}
{'record_id': 101, 'record_year': 2022, 'record_month': 2, 'record_day': 20, 'cost': 53308}
{'record_id': 789, 'record_year': 2023, 'record_month': 8, 'record_day': 26, 'cost': 81993}
{'record_id': 391, 'record_year': 2023, 'record_month': 10, 'record_day': 6, 'cost': 91311}
{'record_id': 695, 'record_year': 2021, 'record_month': 3, 'record_day': 17, 'cost': 77691}
{'record_id': 152, 'record_year': 2022, 'record_month': 6, 'record_day': 3, 'cost': 3382}
{'record_id': 418, 'record_year': 2021, 'record_month': 2, 'record_day': 15, 'cost': 18864}
{'record_id': 459, 'record_year': 2022, 'record_month': 7, 'record_day': 10, 'cost': 65381}
{'record_id': 259, 'record_year': 2022, 'record_month': 9, 'record_day': 18, 'cost': 40541}
{'record_id': 4, 'record_year': 2022, 'record_month': 5, 'record_day': 24, 'cost': 20544}
{'record_id': 699, 'record_year': 2021, 'record_month': 1, 'record_day': 3, 'cost': 62014}
{'record_id': 217, 'record_year': 2022, 'record_month': 3, 'record_day': 9, 'cost': 98382}
{'record_id': 657, 'record_year': 2023, 'record_month': 12, 'record_day': 18, 'cost': 33263}
{'record_id': 394, 'record_year': 2021, 'record_month': 2, 'record_day': 21, 'cost': 6030}
{'record_id': 704, 'record_year': 2023, 'record_month': 3, 'record_day': 26, 'cost': 34858}
{'record_id': 181, 'record_year': 2021, 'record_month': 9, 'record_day': 20, 'cost': 90171}
{'record_id': 470, 'record_year': 2021, 'record_month': 4, 'record_day': 20, 'cost': 93772}
{'record_id': 256, 'record_year': 2022, 'record_month': 1, 'record_day': 16, 'cost': 78283}
{'record_id': 396, 'record_year': 2022, 'record_month': 9, 'record_day': 12, 'cost': 9467}
{'record_id': 622, 'record_year': 2021, 'record_month': 12, 'record_day': 17, 'cost': 60710}
{'record_id': 833, 'record_year': 2023, 'record_month': 2, 'record_day': 4, 'cost': 59272}
{'record_id': 113, 'record_year': 2022, 'record_month': 10, 'record_day': 16, 'cost': 42641}
{'record_id': 983, 'record_year': 2022, 'record_month': 11, 'record_day': 28, 'cost': 65643}
{'record_id': 853, 'record_year': 2022, 'record_month': 11, 'record_day': 28, 'cost': 39213}
{'record_id': 845, 'record_year': 2022, 'record_month': 12, 'record_day': 8, 'cost': 90208}
{'record_id': 974, 'record_year': 2021, 'record_month': 6, 'record_day': 17, 'cost': 68954}
{'record_id': 815, 'record_year': 2022, 'record_month': 7, 'record_day': 16, 'cost': 24739}
{'record_id': 755, 'record_year': 2023, 'record_month': 9, 'record_day': 18, 'cost': 40710}
{'record_id': 233, 'record_year': 2021, 'record_month': 6, 'record_day': 12, 'cost': 49184}
{'record_id': 16, 'record_year': 2021, 'record_month': 2, 'record_day': 7, 'cost': 39811}
{'record_id': 127, 'record_year': 2023, 'record_month': 10, 'record_day': 7, 'cost': 44854}
{'record_id': 956, 'record_year': 2022, 'record_month': 2, 'record_day': 19, 'cost': 92077}
{'record_id': 979, 'record_year': 2023, 'record_month': 3, 'record_day': 1, 'cost': 17866}
{'record_id': 245, 'record_year': 2023, 'record_month': 11, 'record_day': 3, 'cost': 7020}
{'record_id': 122, 'record_year': 2022, 'record_month': 7, 'record_day': 5, 'cost': 35537}
{'record_id': 115, 'record_year': 2022, 'record_month': 12, 'record_day': 6, 'cost': 5837}
{'record_id': 834, 'record_year': 2022, 'record_month': 4, 'record_day': 28, 'cost': 92100}
{'record_id': 463, 'record_year': 2023, 'record_month': 8, 'record_day': 10, 'cost': 53888}
{'record_id': 174, 'record_year': 2023, 'record_month': 2, 'record_day': 26, 'cost': 57685}
{'record_id': 742, 'record_year': 2021, 'record_month': 4, 'record_day': 16, 'cost': 49911}
{'record_id': 212, 'record_year': 2023, 'record_month': 9, 'record_day': 18, 'cost': 43911}
{'record_id': 449, 'record_year': 2022, 'record_month': 7, 'record_day': 6, 'cost': 34020}
{'record_id': 618, 'record_year': 2023, 'record_month': 6, 'record_day': 17, 'cost': 83378}
{'record_id': 818, 'record_year': 2022, 'record_month': 9, 'record_day': 27, 'cost': 56176}
{'record_id': 167, 'record_year': 2022, 'record_month': 8, 'record_day': 14, 'cost': 52049}
{'record_id': 987, 'record_year': 2023, 'record_month': 8, 'record_day': 24, 'cost': 69345}
{'record_id': 469, 'record_year': 2021, 'record_month': 9, 'record_day': 4, 'cost': 32608}
{'record_id': 447, 'record_year': 2022, 'record_month': 12, 'record_day': 18, 'cost': 82653}
{'record_id': 457, 'record_year': 2021, 'record_month': 6, 'record_day': 5, 'cost': 60902}
{'record_id': 382, 'record_year': 2023, 'record_month': 2, 'record_day': 2, 'cost': 96413}
{'record_id': 967, 'record_year': 2023, 'record_month': 7, 'record_day': 24, 'cost': 34164}
{'record_id': 828, 'record_year': 2021, 'record_month': 7, 'record_day': 16, 'cost': 86900}
{'record_id': 84, 'record_year': 2022, 'record_month': 3, 'record_day': 24, 'cost': 62948}

**< 실제 데이터와 합친 최종 데이터 >**

In [106]:
# 최종 진료내역 데이터
records_fin = pd.read_csv("records.csv")
records_fin.head()

,record_id,record_year,record_month,record_day,cost,patient_id,disease_id,doctor_id
0,810,2023,7,11,57323,853,852,442
1,749,2022,2,10,24560,838,510,988
2,902,2022,2,12,15703,347,824,988
3,490,2022,6,15,59357,609,764,925
4,927,2021,3,6,94293,32,65,925

In [107]:
records_fin.tail()

,record_id,record_year,record_month,record_day,cost,patient_id,disease_id,doctor_id
95,457,2021,6,5,60902,229,681,394
96,382,2023,2,2,96413,43,195,601
97,967,2023,7,24,34164,955,137,724
98,828,2021,7,16,86900,201,365,834
99,84,2022,3,24,62948,137,946,601